name: chgk_rating
description: Dart wrapper client for the competitive What? Where? When? rating WebAPIRating https://rating.chgk.info/api-doc
version: 0.0.2
homepage: https://github.com/vmpay/chgk_rating_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0

dev_dependencies:
  test: ^1.16.8
