name: chgk_rating
description: Dart wrapper client for the competitive What? Where? When? rating WebAPIRating https://api.rating.chgk.net/
version: 1.0.1
repository: https://github.com/vmpay/chgk_rating_dart
issue_tracker: https://github.com/vmpay/chgk_rating_dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  mockito: ^5.3.2
  meta: ^1.3.0
  collection: ^1.17.0

dev_dependencies:
  test: ^1.22.2
  build_runner: ^2.3.3
